import type { CommsCategory } from '@/shared/comms/types';

/**
 * The full communication catalogue for TicketRoyality.
 *
 * Built around what this platform actually does — sell tickets, admit people, pay
 * organisers — rather than around a generic SaaS lifecycle. The largest categories are
 * Ticket & Order and Door & Entry because that is where the product lives.
 */
export const COMMS_CATALOGUE: CommsCategory[] = [
  {
    id: 'identity',
    label: 'Identity & Account',
    description: 'Registration, verification and account state for every role.',
    events: [
      { key: 'account.registration.started', label: 'Registration started', subject: 'Welcome to TicketRoyality — confirm your email', severity: 'info', channels: ['email', 'inapp'], audience: ['customer', 'organiser'] },
      { key: 'account.email.verify', label: 'Verify email', subject: 'Confirm your email address', severity: 'warning', channels: ['email'], audience: ['customer', 'organiser'], mandatory: true, note: 'Gates every privileged action — docs/11 §11.13' },
      { key: 'account.email.verified', label: 'Email verified', subject: 'Your email is confirmed', severity: 'success', channels: ['email', 'inapp'], audience: ['customer', 'organiser'] },
      { key: 'account.welcome.customer', label: 'Welcome — customer', subject: 'You are in. Here is what to do first', severity: 'success', channels: ['email', 'inapp'], audience: ['customer'] },
      { key: 'account.welcome.organiser', label: 'Welcome — organiser', subject: 'Your organiser account is being reviewed', severity: 'info', channels: ['email', 'inapp'], audience: ['organiser'] },
      { key: 'account.acu.welcome_bonus', label: 'Welcome credit granted', subject: 'You have {{acu}} AI credits to start with', severity: 'success', channels: ['inapp'], audience: ['customer', 'organiser'] },
      { key: 'account.registration.abandoned', label: 'Registration abandoned', subject: 'Finish setting up your account', severity: 'info', channels: ['email'], audience: ['customer', 'organiser'] },
      { key: 'account.profile.updated', label: 'Profile updated', subject: 'Your profile was updated', severity: 'info', channels: ['inapp'], audience: ['customer', 'organiser'] },
      { key: 'account.deletion.requested', label: 'Deletion requested', subject: 'We received your deletion request', severity: 'warning', channels: ['email', 'inapp'], audience: ['customer', 'organiser'], mandatory: true, note: 'GDPR Art. 17 — must be acknowledged' },
      { key: 'account.deletion.completed', label: 'Deletion completed', subject: 'Your account has been deleted', severity: 'info', channels: ['email'], audience: ['customer', 'organiser'], mandatory: true, note: 'Financial records retained under Art. 17(3)(b) — docs/11 §11.14' },
    ],
  },
  {
    id: 'security',
    label: 'Login & Security',
    description: 'Sign-in, devices, credentials. Almost all mandatory — a security notice you opted out of is a security notice that did not happen.',
    events: [
      { key: 'auth.login.new_device', label: 'New device sign-in', subject: 'New sign-in from a device we have not seen', severity: 'warning', channels: ['email', 'inapp'], audience: ['customer', 'organiser', 'admin'], mandatory: true },
      { key: 'auth.login.suspicious', label: 'Suspicious sign-in', subject: 'Unusual sign-in detected', severity: 'critical', channels: ['email', 'inapp', 'sms'], audience: ['customer', 'organiser', 'admin'], mandatory: true },
      { key: 'auth.password.reset_link', label: 'Password reset link', subject: 'Reset your password', severity: 'info', channels: ['email'], audience: ['customer', 'organiser', 'admin'], mandatory: true },
      { key: 'auth.password.changed', label: 'Password changed', subject: 'Your password was changed', severity: 'success', channels: ['email'], audience: ['customer', 'organiser', 'admin'], mandatory: true },
      { key: 'auth.mfa.code', label: 'Verification code', subject: 'Your verification code is {{code}}', severity: 'info', channels: ['sms', 'email'], audience: ['customer', 'organiser', 'admin'], mandatory: true },
      { key: 'auth.mfa.enabled', label: 'Two-factor enabled', subject: 'Two-factor authentication is on', severity: 'success', channels: ['email', 'inapp'], audience: ['organiser', 'admin'], mandatory: true },
      { key: 'auth.mfa.disabled', label: 'Two-factor disabled', subject: 'Two-factor authentication was turned off', severity: 'warning', channels: ['email', 'sms'], audience: ['organiser', 'admin'], mandatory: true },
      { key: 'auth.account.locked', label: 'Account locked', subject: 'Your account has been locked', severity: 'critical', channels: ['email', 'sms'], audience: ['customer', 'organiser', 'admin'], mandatory: true },
      { key: 'auth.session.revoked', label: 'Session signed out', subject: 'A session was signed out', severity: 'warning', channels: ['email', 'inapp'], audience: ['organiser', 'admin'], mandatory: true },
      { key: 'auth.payout_details.changed', label: 'Payout details changed', subject: 'Your payout destination was changed', severity: 'critical', channels: ['email', 'sms', 'inapp'], audience: ['organiser', 'merchant'], mandatory: true, note: 'The single highest-value fraud target on the platform' },
    ],
  },
  {
    id: 'orders',
    label: 'Ticket & Order',
    description: 'The core path. A buyer who paid and heard nothing assumes fraud.',
    events: [
      { key: 'order.created', label: 'Order started', subject: 'Your order is being processed', severity: 'info', channels: ['inapp'], audience: ['customer'] },
      { key: 'order.paid', label: 'Payment received', subject: 'Payment received — {{amount}}', severity: 'success', channels: ['email', 'inapp', 'push'], audience: ['customer'], mandatory: true, note: 'Contractual. Never opt-outable' },
      { key: 'ticket.issued', label: 'Tickets issued', subject: 'Your tickets for {{event}}', severity: 'success', channels: ['email', 'inapp', 'push', 'whatsapp'], audience: ['customer'], mandatory: true, note: 'This IS the product. Delivery failure is indistinguishable from fraud' },
      { key: 'order.failed', label: 'Payment failed', subject: 'Your payment did not go through', severity: 'warning', channels: ['email', 'inapp'], audience: ['customer'], mandatory: true },
      { key: 'order.abandoned', label: 'Checkout abandoned', subject: 'You left tickets for {{event}} behind', severity: 'info', channels: ['email'], audience: ['customer'], note: 'Marketing — fully opt-outable' },
      { key: 'ticket.transferred_out', label: 'Ticket sent', subject: 'You sent a ticket to {{recipient}}', severity: 'info', channels: ['email', 'inapp'], audience: ['customer'], mandatory: true },
      { key: 'ticket.transferred_in', label: 'Ticket received', subject: '{{actor}} sent you a ticket for {{event}}', severity: 'success', channels: ['email', 'inapp', 'push'], audience: ['customer'], mandatory: true },
      // Hospitality. A table is a larger, slower purchase than a ticket: money arrives
      // in two parts and a guest list is filled in over days, so the buyer needs telling
      // at each step rather than once at the end.
      { key: 'hospitality.table.reserved', label: 'Table reserved', subject: 'Your table for {{event}} is reserved', severity: 'success', channels: ['email', 'inapp'], audience: ['customer'], mandatory: true },
      { key: 'hospitality.balance.due', label: 'Balance due', subject: 'Balance due for your table at {{event}}', severity: 'warning', channels: ['email', 'inapp'], audience: ['customer'], mandatory: true, note: 'Tickets are not issued until this is settled' },
      { key: 'hospitality.booking.settled', label: 'Table paid in full', subject: 'Your table at {{event}} is paid — tickets on the way', severity: 'success', channels: ['email', 'inapp'], audience: ['customer'], mandatory: true },
      { key: 'hospitality.booking.cancelled', label: 'Table cancelled', subject: 'Your table booking for {{event}} was cancelled', severity: 'warning', channels: ['email', 'inapp'], audience: ['customer'], mandatory: true },
      { key: 'order.refund.requested', label: 'Refund requested', subject: 'We received your refund request', severity: 'info', channels: ['email', 'inapp'], audience: ['customer'] },
      { key: 'order.refund.processed', label: 'Refund processed', subject: 'Your refund of {{amount}} is on its way', severity: 'success', channels: ['email', 'inapp'], audience: ['customer'], mandatory: true },
      { key: 'order.refund.declined', label: 'Refund declined', subject: 'About your refund request', severity: 'warning', channels: ['email', 'inapp'], audience: ['customer'], mandatory: true },
      { key: 'offline_payment.submitted', label: 'Mobile money reference submitted', subject: 'We are checking your payment', severity: 'info', channels: ['email', 'inapp', 'whatsapp'], audience: ['customer'], mandatory: true },
      { key: 'offline_payment.verified', label: 'Mobile money verified', subject: 'Payment confirmed — your tickets are ready', severity: 'success', channels: ['email', 'inapp', 'whatsapp', 'push'], audience: ['customer'], mandatory: true, note: 'KODA or admin approval — docs/20' },
      { key: 'offline_payment.declined', label: 'Mobile money not found', subject: 'We could not match your payment', severity: 'warning', channels: ['email', 'inapp', 'whatsapp'], audience: ['customer'], mandatory: true },
      { key: 'waitlist.offer', label: 'Waitlist place available', subject: 'A ticket for {{event}} is yours if you want it', severity: 'success', channels: ['email', 'push', 'sms'], audience: ['customer'], mandatory: true, note: 'Time-boxed offer — SMS because the window is short' },
      { key: 'waitlist.expired', label: 'Waitlist offer expired', subject: 'Your waitlist offer has expired', severity: 'info', channels: ['email', 'inapp'], audience: ['customer'] },
    ],
  },
  {
    id: 'event_changes',
    label: 'Event Changes',
    description: 'Every event in this category is mandatory and ignores quiet hours. A venue change at 17:00 for a 19:00 door is worth waking someone for.',
    events: [
      { key: 'event.cancelled', label: 'Event cancelled', subject: '{{event}} has been cancelled', severity: 'critical', channels: ['email', 'inapp', 'push', 'sms', 'whatsapp'], audience: ['customer'], mandatory: true },
      { key: 'event.postponed', label: 'Event postponed', subject: '{{event}} has moved to {{date}}', severity: 'critical', channels: ['email', 'inapp', 'push', 'sms'], audience: ['customer'], mandatory: true },
      { key: 'event.venue_changed', label: 'Venue changed', subject: 'Important: {{event}} has moved venue', severity: 'critical', channels: ['email', 'inapp', 'push', 'sms'], audience: ['customer'], mandatory: true },
      { key: 'event.time_changed', label: 'Time changed', subject: '{{event}} start time has changed', severity: 'warning', channels: ['email', 'inapp', 'push'], audience: ['customer'], mandatory: true },
      { key: 'event.gate_changed', label: 'Gate changed', subject: 'Use {{gate}} for {{event}}', severity: 'warning', channels: ['inapp', 'push'], audience: ['customer'], mandatory: true },
      { key: 'event.reminder_7d', label: 'Reminder — 7 days', subject: '{{event}} is a week away', severity: 'info', channels: ['email', 'inapp'], audience: ['customer'] },
      { key: 'event.reminder_24h', label: 'Reminder — 24 hours', subject: 'Tomorrow: {{event}}', severity: 'info', channels: ['email', 'push'], audience: ['customer'] },
      { key: 'event.reminder_2h', label: 'Reminder — doors soon', subject: 'Doors at {{time}} — your ticket is ready', severity: 'info', channels: ['push', 'inapp'], audience: ['customer'] },
    ],
  },
  {
    id: 'door',
    label: 'Door & Entry',
    description: 'Live operational signals during an event. Latency matters more than completeness.',
    events: [
      { key: 'door.scan.accepted', label: 'Admitted', subject: 'Admitted to {{event}}', severity: 'success', channels: ['inapp'], audience: ['customer'] },
      { key: 'door.scan.duplicate', label: 'Duplicate scan attempt', subject: 'Duplicate scan on {{event}}', severity: 'warning', channels: ['inapp', 'push'], audience: ['organiser', 'gate_staff'], note: 'Highest-value fraud signal the platform generates — docs/08 §8.12' },
      { key: 'door.congestion', label: 'Gate congestion', subject: 'Queue building at {{gate}}', severity: 'warning', channels: ['push', 'inapp'], audience: ['organiser', 'gate_staff', 'venue'] },
      { key: 'door.offline_mode', label: 'Scanner offline', subject: 'A scanner lost connection at {{gate}}', severity: 'warning', channels: ['push', 'inapp'], audience: ['organiser', 'venue'] },
      { key: 'door.blocklist.added', label: 'Blocklist entry added', subject: 'Entry blocked for {{item}}', severity: 'warning', channels: ['push', 'inapp'], audience: ['gate_staff', 'organiser'], mandatory: true, note: 'Must propagate in seconds — its purpose is the case where someone must not get in now' },
      { key: 'door.capacity_warning', label: 'Approaching capacity', subject: '{{event}} at {{percent}} of capacity', severity: 'warning', channels: ['push', 'inapp'], audience: ['organiser', 'venue'] },
    ],
  },
  {
    id: 'organiser',
    label: 'Organiser & Events',
    description: 'Account approval, event lifecycle, sales milestones.',
    events: [
      { key: 'organiser.approved', label: 'Organiser approved', subject: 'You can start selling', severity: 'success', channels: ['email', 'inapp', 'push'], audience: ['organiser'], mandatory: true },
      { key: 'organiser.rejected', label: 'Organiser rejected', subject: 'About your organiser application', severity: 'warning', channels: ['email', 'inapp'], audience: ['organiser'], mandatory: true },
      { key: 'organiser.suspended', label: 'Organiser suspended', subject: 'Your account has been suspended', severity: 'critical', channels: ['email', 'inapp', 'sms'], audience: ['organiser'], mandatory: true },
      { key: 'event.published', label: 'Event published', subject: '{{event}} is live', severity: 'success', channels: ['email', 'inapp'], audience: ['organiser'] },
      { key: 'event.first_sale', label: 'First ticket sold', subject: 'You sold your first ticket for {{event}}', severity: 'success', channels: ['push', 'inapp'], audience: ['organiser'] },
      { key: 'event.milestone', label: 'Sales milestone', subject: '{{event}} is {{percent}} sold', severity: 'success', channels: ['push', 'inapp'], audience: ['organiser'] },
      { key: 'event.sold_out', label: 'Sold out', subject: '{{event}} is sold out', severity: 'success', channels: ['email', 'push', 'inapp'], audience: ['organiser'] },
      { key: 'event.slow_sales', label: 'Sales behind forecast', subject: '{{event}} is tracking below forecast', severity: 'warning', channels: ['email', 'inapp'], audience: ['organiser'], note: 'cro.v1 — docs/03 §3.3' },
      { key: 'event.publish_blocked', label: 'Publish blocked', subject: '{{event}} cannot go live yet', severity: 'warning', channels: ['inapp'], audience: ['organiser'], note: 'Pre-publish checklist — docs/04 M22' },
    ],
  },
  {
    id: 'payouts',
    label: 'Payouts & Finance',
    description: 'Money leaving the platform. Every state change is mandatory.',
    events: [
      { key: 'payout.requested', label: 'Payout requested', subject: 'We received your payout request', severity: 'info', channels: ['email', 'inapp'], audience: ['organiser'], mandatory: true },
      { key: 'payout.approved', label: 'Payout approved', subject: 'Your payout of {{amount}} is on its way', severity: 'success', channels: ['email', 'inapp', 'push'], audience: ['organiser'], mandatory: true },
      { key: 'payout.paid', label: 'Payout completed', subject: '{{amount}} has been sent', severity: 'success', channels: ['email', 'inapp'], audience: ['organiser'], mandatory: true },
      { key: 'payout.blocked_kyb', label: 'Payout blocked — verification', subject: 'Verification needed before we can pay you', severity: 'warning', channels: ['email', 'inapp'], audience: ['organiser'], mandatory: true, note: 'Legally cannot pay without KYB — docs/11 §11.14' },
      { key: 'payout.failed', label: 'Payout failed', subject: 'Your payout could not be completed', severity: 'critical', channels: ['email', 'inapp', 'sms'], audience: ['organiser'], mandatory: true },
      { key: 'invoice.issued', label: 'Invoice issued', subject: 'Invoice {{number}} is ready', severity: 'info', channels: ['email', 'inapp'], audience: ['organiser'], mandatory: true },
      { key: 'chargeback.opened', label: 'Chargeback opened', subject: 'A chargeback was raised on {{event}}', severity: 'critical', channels: ['email', 'inapp'], audience: ['organiser', 'admin'], mandatory: true },
      { key: 'chargeback.deadline', label: 'Chargeback deadline near', subject: 'Evidence due in {{hours}} hours', severity: 'critical', channels: ['email', 'push', 'inapp'], audience: ['admin'], mandatory: true, note: 'Most chargebacks are lost unanswered — docs/12 §12.13' },
    ],
  },
  {
    id: 'hospitality',
    label: 'VIP & Hospitality',
    description: 'Named guests, deposits, dietary requirements. Higher value, higher touch.',
    events: [
      { key: 'hospitality.booking.confirmed', label: 'Package booked', subject: 'Your {{item}} package is confirmed', severity: 'success', channels: ['email', 'inapp'], audience: ['customer', 'host'], mandatory: true },
      { key: 'hospitality.deposit.received', label: 'Deposit received', subject: 'Deposit received for {{item}}', severity: 'success', channels: ['email'], audience: ['customer', 'host'], mandatory: true },
      { key: 'hospitality.balance.due', label: 'Balance due', subject: 'Balance of {{amount}} due by {{date}}', severity: 'warning', channels: ['email', 'inapp'], audience: ['customer'], mandatory: true },
      { key: 'hospitality.guests.due', label: 'Guest names needed', subject: 'Guest names needed by {{date}}', severity: 'warning', channels: ['email', 'inapp'], audience: ['customer', 'host'], mandatory: true, note: 'Caterer headcount deadline — docs/04 M21' },
      { key: 'hospitality.guests.locked', label: 'Guest list locked', subject: 'Your guest list is now final', severity: 'info', channels: ['email', 'inapp'], audience: ['customer', 'host'] },
      { key: 'hospitality.concierge.reply', label: 'Concierge reply', subject: 'A reply about your {{item}} booking', severity: 'info', channels: ['email', 'inapp', 'push'], audience: ['customer'] },
    ],
  },
  {
    id: 'growth',
    label: 'Promoter & Creator',
    description: 'Allocation, attribution and commission for the distribution network.',
    events: [
      { key: 'creator.verified', label: 'Creator verified', subject: 'You are verified — 1% on every ticket', severity: 'success', channels: ['email', 'inapp'], audience: ['creator'] },
      { key: 'creator.tier_changed', label: 'Tier changed', subject: 'Your creator tier is now {{item}}', severity: 'info', channels: ['email', 'inapp'], audience: ['creator'], note: 'Tiers fall as well as rise — engagement is re-checked monthly' },
      { key: 'creator.commission.confirmed', label: 'Commission confirmed', subject: '{{amount}} confirmed from {{event}}', severity: 'success', channels: ['inapp', 'push'], audience: ['creator'] },
      { key: 'creator.payout.sent', label: 'Creator payout sent', subject: 'Your {{amount}} payout is on its way', severity: 'success', channels: ['email', 'inapp'], audience: ['creator'], mandatory: true },
      { key: 'creator.disclosure_warning', label: 'Disclosure missing', subject: 'Your post needs an ad disclosure', severity: 'warning', channels: ['email', 'inapp'], audience: ['creator'], mandatory: true, note: 'ASA and FTC requirement — docs/04 M26' },
      { key: 'promoter.allocation.assigned', label: 'Allocation assigned', subject: 'You have {{item}} tickets to sell for {{event}}', severity: 'info', channels: ['email', 'inapp'], audience: ['creator'] },
      { key: 'referral.rewarded', label: 'Referral rewarded', subject: 'Your friend went — here is your credit', severity: 'success', channels: ['email', 'inapp', 'push'], audience: ['customer'], note: 'Released on attendance, not purchase — docs/04 M26' },
    ],
  },
  {
    id: 'acu',
    label: 'AI Credits & Agents',
    description: 'ACU balance and agent output. Cost visibility is the point.',
    events: [
      { key: 'acu.low_balance', label: 'Low credit balance', subject: 'You have {{acu}} AI credits left', severity: 'warning', channels: ['inapp', 'email'], audience: ['organiser', 'customer'] },
      { key: 'acu.exhausted', label: 'Credits exhausted', subject: 'AI features are paused until you top up', severity: 'warning', channels: ['inapp', 'email'], audience: ['organiser', 'customer'], mandatory: true, note: 'Hard stop, never an overdraft — docs/10 §10.6' },
      { key: 'acu.topup.completed', label: 'Top-up completed', subject: '{{acu}} credits added', severity: 'success', channels: ['email', 'inapp'], audience: ['organiser', 'customer'], mandatory: true },
      { key: 'acu.admin_grant', label: 'Credit granted', subject: 'You were granted {{acu}} credits', severity: 'success', channels: ['inapp', 'email'], audience: ['organiser', 'customer'], mandatory: true, note: 'Reason is always shown — docs/17 §17.6 F4' },
      { key: 'agent.draft_ready', label: 'Agent draft ready', subject: 'Your {{item}} draft is ready to review', severity: 'info', channels: ['inapp', 'push'], audience: ['organiser'] },
      { key: 'agent.approval_needed', label: 'Agent needs approval', subject: 'Action needed: {{item}}', severity: 'warning', channels: ['inapp', 'push', 'email'], audience: ['organiser', 'admin'], mandatory: true, note: 'L1 autonomy — nothing proceeds without this' },
      { key: 'agent.escalated', label: 'Agent escalated', subject: 'An agent escalated {{item}}', severity: 'critical', channels: ['email', 'push', 'inapp'], audience: ['admin'], mandatory: true },
    ],
  },
  {
    id: 'compliance',
    label: 'Compliance & Legal',
    description: 'Consent, verification and regulatory notices. All mandatory by definition.',
    events: [
      { key: 'kyb.started', label: 'Verification started', subject: 'Verification of {{item}} has started', severity: 'info', channels: ['email', 'inapp'], audience: ['organiser', 'merchant'], mandatory: true },
      { key: 'kyb.documents_needed', label: 'Documents needed', subject: 'We need documents to verify {{item}}', severity: 'warning', channels: ['email', 'inapp'], audience: ['organiser', 'merchant'], mandatory: true },
      { key: 'kyb.approved', label: 'Verification approved', subject: '{{item}} is verified', severity: 'success', channels: ['email', 'inapp'], audience: ['organiser', 'merchant'], mandatory: true },
      { key: 'kyb.rejected', label: 'Verification rejected', subject: 'About your verification', severity: 'warning', channels: ['email', 'inapp'], audience: ['organiser', 'merchant'], mandatory: true },
      { key: 'privacy.consent_request', label: 'Consent request', subject: 'We need your consent', severity: 'info', channels: ['email', 'inapp'], audience: ['customer', 'organiser'], mandatory: true },
      { key: 'privacy.data_export_ready', label: 'Data export ready', subject: 'Your data export is ready', severity: 'success', channels: ['email'], audience: ['customer', 'organiser'], mandatory: true },
      { key: 'legal.terms_updated', label: 'Terms updated', subject: 'We have updated our terms', severity: 'info', channels: ['email', 'inapp'], audience: ['customer', 'organiser'], mandatory: true },
    ],
  },
  {
    id: 'platform',
    label: 'Platform & Support',
    description: 'Status, incidents and support threads.',
    events: [
      { key: 'system.maintenance_scheduled', label: 'Scheduled maintenance', subject: 'Maintenance on {{date}}', severity: 'info', channels: ['email', 'inapp'], audience: ['organiser', 'admin'] },
      { key: 'system.incident', label: 'Service disruption', subject: 'We are investigating a service issue', severity: 'critical', channels: ['email', 'inapp'], audience: ['organiser', 'admin'], mandatory: true },
      { key: 'system.restored', label: 'Service restored', subject: 'Service is back to normal', severity: 'success', channels: ['email', 'inapp'], audience: ['organiser', 'admin'], mandatory: true },
      { key: 'support.ticket_created', label: 'Support ticket created', subject: 'We got your message — ticket {{number}}', severity: 'info', channels: ['email', 'inapp'], audience: ['customer', 'organiser'] },
      { key: 'support.ticket_replied', label: 'Support reply', subject: 'A reply on ticket {{number}}', severity: 'info', channels: ['email', 'inapp', 'push'], audience: ['customer', 'organiser'] },
      { key: 'support.ticket_resolved', label: 'Support resolved', subject: 'Ticket {{number}} is resolved', severity: 'success', channels: ['email', 'inapp'], audience: ['customer', 'organiser'] },
    ],
  },
  {
    id: 'marketing',
    label: 'Marketing & Discovery',
    description: 'Fully opt-outable. Nothing here is ever marked mandatory, and nothing mandatory ever carries marketing.',
    events: [
      { key: 'marketing.recommendation', label: 'Recommended for you', subject: 'You might like {{event}}', severity: 'info', channels: ['email', 'push'], audience: ['customer'] },
      { key: 'marketing.followed_organiser', label: 'A followed organiser posted', subject: '{{actor}} announced {{event}}', severity: 'info', channels: ['email', 'push', 'inapp'], audience: ['customer'], note: 'Requires follows.notify — consent is the lawful basis, docs/08 §8.15a' },
      { key: 'marketing.presale_access', label: 'Presale access', subject: 'Early access to {{event}}', severity: 'info', channels: ['email', 'push'], audience: ['customer'] },
      { key: 'marketing.weekly_digest', label: 'Weekly digest', subject: 'What is on this week', severity: 'info', channels: ['email'], audience: ['customer'] },
      { key: 'marketing.post_event_review', label: 'Review request', subject: 'How was {{event}}?', severity: 'info', channels: ['email', 'push'], audience: ['customer'] },
    ],
  },
];
